% Energy Economics Author Guide: 
% https://www.elsevier.com/journals/energy-economics/0140-9883/guide-for-authors

\documentclass[review]{elsarticle}

\usepackage{lineno}
\modulolinenumbers[5]


%% Package imports %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\usepackage{amsfonts}           % For access to \checkmark.
\usepackage{amsmath}            % For better symbol decorations
\usepackage{booktabs}           % For nice table rules
\usepackage{chngcntr}           % To get figure and table numbering correct in the appendices
\usepackage[makeroom]{cancel}   % To show terms go to zero
\usepackage[inline]{enumitem}   % For inline enumeration
\usepackage{multicol}           % For multi-column layout
\usepackage{multirow}           % For multi-row layout
\usepackage{nccmath}            % For the \useshortskip command above equations
\usepackage{parcolumns}         % For multi-column layout
\usepackage{pdflscape}          % For landscape environment \begin{landscape} ... \end{landscape}
\usepackage{soul}               % For text highlighting
\usepackage[most]{tcolorbox}    % For color highlighting of text
\usepackage{tikz}               % For diagrams
\usetikzlibrary{arrows,positioning}
\usepackage{ulem}               % For strikeout command (\sout)
\usepackage{xcolor}             % For ... colors

\usepackage{hyperref} % hyperref should be the last package loaded


%% Macros defined by authors %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/macros.tex}


%% Journal %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\journal{Energy Economics}


%% Bibliography style %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\bibliographystyle{model2-names.bst}\biboptions{authoryear}


\begin{document}
%\SweaveOpts{concordance=TRUE}

\begin{frontmatter}

%% Title %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\title{Toward a Comprehensive Energy-Economy \\
        Analytical Framework for \\
        Energy Rebound}


%% Authors %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\author[MKH_address]{Matthew Kuperus Heun\corref{corr_author}}
\cortext[corr_author]{Corresponding author}
\ead{mkh2@calvin.edu}

\author[GS_address]{Gregor Semienuik}
\ead{gsemieniuk@umass.edu}

\author[PB_address]{Paul E. Brockway}
\ead{P.E.Brockway@leeds.ac.uk}


%% Addresses %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\address[MKH_address]{Engineering Department,\\
Calvin University, 3201 Burton St. SE,\\
Grand Rapids, MI, 49546, USA.}

\address[GS_address]{Political Economy Research Institute \& Department of Economics,\\
University of Massachusetts at Amherst, 412 North Pleasant St.,\\
Amherst, MA, 01002, USA}

\address[PB_address]{Sustainability Research Institute, School of Earth and Environment,\\
University of Leeds,\\
Leeds, LS2 9JT, UK}


%% Abstract %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{abstract}
A concise and factual abstract is required.
The abstract should state briefly 
the purpose of the research, 
the principal results, and
major conclusions. 
An abstract is often presented separately from the article, 
so it must be able to stand alone.
For this reason, References should be avoided, but if essential, 
then cite the author(s) and year(s).
Also, non-standard or uncommon abbreviations should be avoided, but
if essential they must be defined at their first mention in the abstract itself.
\end{abstract}


%% Keywords %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% maximum of 6 keywords, using American spelling and avoiding general and plural terms and multiple concepts 
% (avoid, for example, 'and', 'of'). Be sparing with abbreviations: 
% only abbreviations firmly established in the field may be eligible. 
% These keywords will be used for indexing purposes.

% Up to 6 standard JEL codes. The available codes may be accessed at JEL, 
% https://www.aeaweb.org/jel/guide/jel.php   

\begin{keyword}
% Maximum of 6 keywords. \texttt{elsarticle.cls}\sep \LaTeX\sep Elsevier \sep template
% Maximum of 6 JEL codes. \MSC[2010] 00-01 \sep  99-00
% JEL codes: https://www.aeaweb.org/jel/guide/jel.php
Energy rebound \sep Conservation \sep Backfire \sep 
Energy efficiency \sep Energy economics \sep Elasticity of substitution
\end{keyword}

\end{frontmatter}

<<setup, echo=FALSE, message=FALSE>>=
library(dplyr)
library(magrittr)
library(ReboundTools)
library(tidyr)
library(xtable)
@

\linenumbers


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Terminology}
\label{sec:terminology}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Some guidance regarding terms and style for the paper.

\begin{enumerate}

  \item What do we call a thing that converts electricity to light?  \emph{electric lamp}, (not light bulb).

  \item What do we call assumed/known information? \emph{parameters} (not variables).
  
  \item Use double-dash (--) for em-dash.
  
  \item Use back ticks (``) and single quotes ('') for quotation marks.

\end{enumerate}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction (total: 1000 words)}
\label{sec:introduction}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%++++++++++++++++++++++++++++++
\subsection{Energy rebound background}
\label{sec:background}
%++++++++++++++++++++++++++++++

% General discussion of the importance of rebound, 
% non-microeconomic references.
% Here are some references from Matt's database that you may want to include:
% \citet{Jevons:1866uy}, 
% \citet{Saunders:1992aa, Saunders:2000aa}, 
% \citet{Sorrell:2007um, Sorrell:2009cg, Sorrell:2010ul},
% \citet{Brockway:2017a}, 
% \citet{Tsao:2010},
% \citet{Chitnis:2015}, 
% \citet{Stapleton:2016}, 
% \citet{Sun:2018aa}, 
% \citet{Fullerton:2019aa},
% etc.
% 
% More studies on large rebound.
% What is missing is an overall framework for rebound to catch all aspects.
% Some people have captured parts.
% 
% We develop framework itself. 
% Follow-on question: need for a case-study example of exercising the framework.
% We provide a guide for application.
% We make it operational.


Energy rebound is a phenomenon whereby 
some expected energy savings do not occur 
after an energy efficiency upgrade (EEU), 
due to various behavior and market responses.

+++
This is the merged edit of MKH's and my suggested changes to avoid circularity. ---GS
+++

The roots of energy rebound can be traced back to William Stanley \citet{Jevons:1866uy}
who, in an 1865 report entitled \emph{The Coal Question},
suggested that
``[i]t is wholly a confusion of ideas to suppose that the economical use of fuel 
is equivalent to a diminished consumption. 
The very contrary is the truth.''
A hundred years later, the 1970s oil crises returned the focus to energy efficiency
and the debate over the size and magnitude of rebound heated up. 
On one side, \citet{Brookes1979, Brookes1990} and \citet{Khazzoom1980} 
suggested that energy rebound could be large, 
while others, 
including \citet{Lovins1988} and \citet{Grubb1990, Grubb1992},
claimed that rebound was small.

The so-called \emph{Khazzoom-Brookes Postulate}~\citep{Saunders:1992aa}
is restated by \citet[p.~212]{Herring1999} as
``increased energy-efficiency at the microeconomic level,
while leading to a reduction of energy use at this level, 
leads not to a reduction, but instead to an increase in energy use, 
at the national, or macroeconomic level.''
%The macroeconomic feedback mechanisms and their
%size lie at
The scale
****
magnitude?---MKH
****
of macroeconomic feedback gets to 
***I placed some alternative text above in comments---PEB***
the heart of the debate,
which continues today.
Advocates of small rebound (say, less than 50~\%),
such as \citet{Gillingham:2013aa, Gillingham2016},
suggest ``the rebound effect is overplayed,'' 
while others, 
such as \citet{Saunders2015}, 
claim the evidence for large rebound
(greater than, say, 50~\% and in some cases above 100~\%, which is known as ``backfire'')
is growing.

The topic of energy rebound is important;
it is much more than an academic debate, 
because there is a lot at stake.
We see three areas of rebound concern: 
hampering of carbon reduction efforts, 
increases to resource and material consumption rates, 
and 
policy-making that largely neglects rebound.
First, to meet our Paris carbon reduction targets~\citep{masson-delmotte2018},
increasing energy efficiency is expected to deliver 
decreasing energy consumption and CO$_2$ emissions
amidst continued economic growth.
Taking just one example,
by 2040
energy efficiency contributes 44~\% of 
energy-related global carbon emissions reductions in
the International Energy Agency's Sustainable Development scenario relative to
its New Policies scenario~\citep[Fig.~3.15, p.~139]{International-Energy-Agency:2017b}.
However as \citet{Brockway2020} note, 
such reductions in energy consumption 
would represent a structural break with the historical record
of close energy-GDP coupling,
assuming continued economic growth.
Second, the interactions between energy rebound
and increasing material and resource requirements
are significant~\citep{VandenBergh2009, FontVivanco2018}.
Given the global coupling of material consumption
to economic growth ~\citep{Haberl2020, Wiedmann2020}, 
it may not possible to separate energy rebound from rising material consumption and resource extraction.
Third, energy rebound is rarely included in either 
policy-making~\citep{fontvivanco2016}
or energy~\citep{Brockway2020} models, 
limiting our ability to assess the interactions among
rebound, 
carbon emissions, and
material and resource consumption.
Thus, we believe estimating the magnitude 
of energy rebound is a crucially important goal.


%++++++++++++++++++++++++++++++
\subsection{Rebound typologies}
\label{sec:rebound_typologies}
%++++++++++++++++++++++++++++++

One of the challenges to better understanding energy rebound is its many
aspects, mechanisms, and effects.
The most common rebound typologies 
distinguish between microeconomic effects (direct and indirect)
and 
macroeconomic effects
~\citep{greening2000, Barker2009, FontVivanco2018}. 
~\citet{greening2000} split total rebound 
into two parts:
microeconomic rebound (direct and indirect) and
macroeconomic (economy-wide effects and transformational effects).
+++
Greening et al actually talk about a 'macroeconomic view' (p.390) and 'macroeconomic implications' (p.399) but not a macroeconomic rebound ---GS
+++ 
\citet{Jenkins2011} break up microeconomic rebound effects into
direct (income and substitution effects) and 
indirect (respending and embodied effects), 
while \citet{Sorrell:2009cg} 
sets out five macroeconomic rebound effects:
embodied energy effects, respending effects, output effects, energy market effects, and composition effects.
\citet{Santarius2016} and \citet{Lange2019} distinguish 
meso (i.e., sector) scale rebound
from micro and macro rebound.
\citet{VandenBergh2011} distinguishes 14 types of rebound, 
providing, perhaps, the greatest complexity. 
Table~\ref{tab:typology} 
attempts to summarize and reconcile some of the existing typologies.
\citet{madlener2016}, 
reviewing 35 years of rebound research, noted that 
``the reader is sometimes overwhelmed (at best) and often confused (at worst) 
by the many different versions'' of rebound typologies.

\begin{table}
\caption{Rebound typology based on \citet{greening2000}, \citet{Jenkins2011}, and \citet{Thomas:2013ab}.
         **** We need to move Emplacement effects ahead of substitution and income effects 
              to maintain same order as rest of paper.---MKH ****
         **** Convert to a \LaTeX{} table?---MKH ****}
\centering
\includegraphics[width=1\linewidth]{figure_other/typology.pdf}
\label{tab:typology}
\end{table}


%++++++++++++++++++++++++++++++
\subsection{Empirical studies on the magnitude of energy rebound}
\label{sec:empirical_studies}
%++++++++++++++++++++++++++++++

\citet{Sorrell:2007um} provided an important systematic review of energy rebound estimates,
considering over 500 studies and reports from around the world.
He found 
that the most prevalent type of study focused on direct (microeconomic) rebound 
at the household level, with studies typically estimating small rebound magnitudes (10--30~\%).
In contrast, Sorrell noted that evidence for macroeconomic rebound 
was much weaker but could produce larger magnitudes, 
stating ``there are few published studies and these have a number 
of flaws. \ldots{} 
While little confidence can be placed in the available estimates, 
several studies suggest that economy-wide [i.e., macroeconomic] rebound effects may frequently exceed 50~\%.''
Since the~\citet{Sorrell:2007um} review,
empirical estimates
of household-level energy rebound
at the microeconomic scale (direct and indirect)
continue to suggest relatively small
microeconomic rebound magnitudes
of less than 40~\%~\citep{Greene2012, Thomas:2013ab, Antal:2014aa, Chitnis2014, Stapleton:2016}.
Commonly, microeconomic estimates are based on own sector (direct)
and/or
cross-sector (indirect, re-spending) price elasticities,
as set out by \citet{Gillingham2016}.

Meantime, estimates of macroeconomic rebound are very rare
[e.g.,~\citet{Barker2009}]. 
Instead, more common -- but still quite rare -- are studies 
which estimate total rebound
[i.e., sum of microeconomic and macroeconomic rebound 
as shown in Table~\ref{tab:typology}]
have progressed in terms of numbers of studies and methods.
****
Is the preceding sentence complete?---MKH
****
A recent review of studies by \citet{Brockway2020} 
found 
the most common method is via a dominant group of CGE-based studies, 
such as \citet{Lecca2014} and \citet{Wei2017},
with a mean total rebound estimate (from 21 reviewed studies) of around 60~\%. 
The remaining approaches split into three sub-methods: non-CGE macroeconomic models
(e.g., \citet{Barker2009} and \citet{Lemoine2019}),
econometric analysis (e.g., \citet{Wei2019} and \citet{Bruns2019}), and
productivity or growth accounting studies (e.g., \citet{Lin2015}).
The magnitude of total energy rebound from these non-CGE methods 
was also found to be over 50~\%,
leading the review authors \citet{Brockway2020} 
to conclude that total rebound magnitudes 
were ``larger than commonly assumed.''
Finally, increasing empirical support is emerging for 
even larger total rebound estimates from 
the producer side \citep{Saunders2013a} and for developing and 
industrializing countries~\citep{VanBenthem2015, Brockway:2017a}.


%++++++++++++++++++++++++++++++
\subsection{The need for a more comprehensive energy rebound analytical framework}
\label{sec:need_comprehensive}
%++++++++++++++++++++++++++++++

Much of the early work on rebound theory was at the microeconomic scale,
focusing on direct and indirect rebound via price elasticities (e.g.,~\citet{Schipper2000}).
Other microeconomic advances include those by 
\citet{thomas:2013aa}, who set out a detailed framework of direct and indirect microeconomic effects;
\citet{Borenstein:2015aa},
who provided a detailed treatment of rebound into income and substitution effects;
and \citet{Sun:2018aa}, who considered direct rebound including device effects.
However, lifecycle and end of life device effects are still not typically considered. 

At the macroeconomic scale,
\citet{Saunders:1992aa} made the earliest attempt
at a theoretical framework for total energy rebound
based on neo-classical aggregate production functions (APFs).
Later works continued the APF approach, including
\citet{Saunders:2000aa, Saunders2008},
\citet{Wei2017}, and
\citet{Brockway:2017a}.
\citet{Grepperud2004} provide one of the first
general equilibrium frameworks for rebound
(overcoming previous criticisms of partial equilibrium frameworks **** REF ****),
and were followed, among others, by general equilibrium models, including
\citet{Wei2010},
\citet{Lemoine2019}, and
\citet{Fullerton:2019aa}.
Extensions at the macroeconomic scale importantly include the 
linkage to resource and material use, such as the study by ~\citet{Magee2017},
who extended rebound theory to study the material impacts of 
information and communications technology (ICT),
finding little evidence of dematerialization.
**** Here is where I think we can add the  
~\citet{Zink2017}
circular economy reference.---PEB
Need a sentence around the Zink reference to show how it fits with the rest of the paragraph.---MKH ****
Despite the growth of macroeconomic modeling frameworks to 
estimate overall, or total rebound, three key issues remain. 
First, by definition macroeconomic models
work in aggregate variable space when estimating total rebound.
+++
Are you excluding general equilibrium models from macroeconomic modeling frameworks? If so, I am confused by this exclusion and would like to understand your argument better. ---GS
+++ 
Therefore, macroeconomic models rarely discriminate microeconomic and macroeconomic rebound components.
Second, following on, macroeconomic models of rebound lack linkages
between microeconomic and macroeconomic effects. 
The potential amplification from smaller, microeconomic rebound effects to
a larger, macroeconomic effect has been described as the energy productivity effect~\citep{Dimitropoulos2007, Sorrell:2010ul}
or, simply, a multiplier effect ~\citep{Borenstein:2015aa, Lange2019},
which occurs when
``the economy [expands] by more than the private income gain
enjoyed by the owner of the upgraded appliance'' \citep[p.~11]{Borenstein:2015aa}.
The size of this productivity multiplier remains probably the most central of all issues
within the rebound debate.
On one side, \citet{Howarth1997} and \citet{Schipper2000}
claim that the macroeconomic rebound multiplier is small. 
On the other, \citet{Aucott2014}, \citet{Enflo2009}, and \citet{Bataille2017}
are among those who claim the macroeconomic multiplier effect is much larger. 
\citet{Dimitropoulos2007} suggested that
``One of the main reasons behind the debate is the lack of a rigorous theoretical framework
that can describe the mechanisms and consequences of 
the rebound effect at the macro-economic level.''
In a recent review on energy productivity, 
\citet{Elkomy2020} found that
``[w]hile many researchers suggest that energy and productivity are linked, 
there is relatively little consensus in the empirical literatures 
either confirming or rejecting these views. 
In some cases (notably the relationship between capital and energy), 
we do not appear to have robust methodologies for making empirical assessments.''
Therefore it would be advantageous to have an energy-economy analytical framework
that allows for such productivity effects to occur, 
linking microeconomic and macroeconomic scales.
A third issue is that estimates of total rebound magnitudes are
generated by macroeconomic frameworks
are typically contingent upon the type of production function assumed
(Cobb-Douglas, CES, etc.) and
choice of substitution elasticity.
As \citet[p.~2207-2208]{Saunders2008} noted,
``choice of production/cost function can pre-determine the results related to rebound\ldots{}
[and choosing] values for these [elasticity of substitution] parameters
is tantamount to assuming rebound results.''

In summary, we find there is a strategic need for
a more detailed and comprehensive energy rebound framework, 
one that 
%
\begin{enumerate*}[label={(\alph*)}]
	
  \item is built from microeconomic foundations, 
  
  \item carefully distinguishes among the microeconomic components shown in Table~\ref{tab:typology}, and
  
  \item incorporates macroeconomic productivity multiplier effects shown in Table~\ref{tab:typology}. 

\end{enumerate*}
%

% In addition, the development of a rebound analytical framework with the above characteristics provides a way to connect
% engineers and product designers
% (who usually focus on micro efficiency and the device level) and
% economists 
% (some of whom focus on the macroeconomic scale).


%++++++++++++++++++++++++++++++
\subsection{Need, aim, contributions, and structure}
\label{sec:aim_contribution_structure}
%++++++++++++++++++++++++++++++

**** Be sure we hit all of need, aim, contributions, and structure. ****

The aim of this paper is to fill the gap in the literature identified above.
We build on the microeconomic foundations laid by \citet{Borenstein:2015aa}
by defining six microeconomic components of rebound
(direct and indirect rebound for 
emplacement, substitution, and income effects),
with linkage to macroeconomic rebound components via a multiplier effect,
as shown in Table~\ref{tab:typology}.
We also demonstrate application of the framework
by calculating energy rebound associated with 
purchase and use of a fuel-efficient automobile.   

Thus, this paper's contribution to the rebound literature is
the development and presentation of a more-comprehensive
energy-economy rebound analysis framework, 
a ``comprehensive rebound framework'' for short.
The comprehensive rebound framework provides the following benefits:
%
\begin{enumerate*}[label={(\alph*)}]
	
  \item it untangles and clarifies interrelated aspects of energy rebound,
  
  \item it unifies several concepts of energy rebound, 
  
  \item it connects engineers and product designers
        (who usually focus on micro efficiency and the device level) and
        economists 
        (some of whom focus on the macroeconomic scale), and
        ****
        I moved this ``benefit'' from the end of the section above. 
        Do we like it here?
        Do we like this benefit?
        (Although this is important to me, personally, 
        we don't really speak much about this benefit elsewhere in the paper.
        It seems like we should re-connect to each of these benefits later in the paper.
        If we don't re-connect, maybe that means we should delete the benefit?)---MKH
        ****
  
  \item it enables consideration of the potential energy rebound of prospective energy policy options, 
        thereby providing insight to the energy policymaking process.
    
\end{enumerate*}

The remainder of this paper is structured as follows.
Section~\ref{sec:framework} describes the comprehensive analytical framework.
Section~\ref{sec:examples} provides two calculation examples.
Section~\ref{sec:discussion} discusses the results, and 
Section~\ref{sec:conclusion} concludes.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Methods: development of the comprehensive analytical framework (MKH, currently at 2222 words, target was 1500 words)}
\label{sec:framework}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

In this section, we develop a mathematical model 
for the comprehensive rebound framework.
We assume a device (say, an automobile)
that consumes final energy (say, gasoline) at a rate $\rbempl{E}$ (in MJ/year).
The final energy is available at price $\bempl{p}_E$ (in \$/MJ).
The device provides a rate of energy service $\rbempl{q}_s$ (in vehicle km/year)
with final-energy-to-service efficiency $\bempl{\eta}$ (in km/MJ).

An energy efficiency upgrade (EEU) increases
final-energy-to-service efficiency such that
$\aprod{\eta} > \bempl{\eta}$,
typically, but not always,
at an increased financial cost rate to
procure (capital cost), operate, maintain, and dispose of the device
**** PB: GS suggests a citation here that indicates upgrades are usually more costly.---MKH ****,
such that
$\raprod{C}_{cap} > \rbempl{C}_{cap}$ and 
$\raprod{C}_{\md} > \rbempl{C}_{\md}$.
As final-energy-to-service efficiency~($\eta$) increases,
the price of the energy service~($p_s$) declines.
The final energy price ($p_E$) is assumed to be exogenous
($\aprod{p}_E = \bempl{p}_E$),
so the final energy purchaser (i.e., the device owner) is a price taker.
(Relaxing the exogenous final energy price assumption
would require a full-economy model that is beyond the scope of this paper.)

Note that
the vocabulary and mathematical notation for rebound is extensive;
Fig.~\ref{fig:flowchart} and Appendix~\ref{sec:nomenclature} provide guides to 
notation elements (symbols, Greek letters, decorations, and subscripts)
used throughout the paper.
(Fig.~\ref{fig:flowchart} shows the order of discussion for rebound effects; 
it does not necessarily represent 
the progression of rebound effects through time.)
The notation elements 
can be mixed to comprise a rich and expressive ``language'' of energy rebound.
We use colored backgrounds on rebound effects for visual convenience. 

\begin{figure}
\centering
  % The file is a Tikz picture.
  \input{pieces/flowchart.tex}
\caption{Flowchart of effects and decorations.}
\label{fig:flowchart}
\end{figure}

Later (Sections~\ref{sec:empl_effect_main_paper}--\ref{sec:prod_effect_main_paper}), 
we walk through the several conceptual stages of rebound, including
the device upgrade and four rebound effects, and 
we derive rebound expressions for each. 
But first 
we define rebound relationships 
(Section~\ref{sec:rebound_relationships}) and 
typical energy and cost relationships (Section~\ref{sec:energy_and_cost_relationships})
for the analysis.


%++++++++++++++++++++++++++++++
\subsection{Rebound relationships}
\label{sec:rebound_relationships}
%++++++++++++++++++++++++++++++

Energy rebound is defined as

\begin{equation} \label{eq:Re_def}
  Re \equiv 1 - \frac{\text{actual final energy savings rate}}{\text{expected final energy savings rate}} \; ,
\end{equation}
%
where both actual and expected final energy savings rates are expected positive.
Final energy ``takeback'' is the rate at which final energy savings are eroded by rebound effects,
and the actual final energy savings rate is the expected final energy savings rate less takeback.
Note that takeback can be negative, indicating an increase in the final energy savings rate
relative to the expected final energy savings rate, sometimes called hyperconservation.
Thus,

\begin{equation}
  Re = 1 - \frac{\text{expected final energy savings rate} - \text{takeback}}{\text{expected final energy savings rate}} \; ,
\end{equation}
%
or

\begin{equation}
  Re = 1 - 1 + \frac{\text{takeback}}{\text{expected final energy savings rate}} \; .
\end{equation}
%
Simplifying gives

\begin{equation} \label{eq:Re_takeback}
  Re = \frac{\text{takeback}}{\text{expected final energy savings rate}} \; .
\end{equation}
%
Thus, energy rebound can be given by either Eq.~(\ref{eq:Re_def}) or Eq.~(\ref{eq:Re_takeback}).

We define rebound at the final energy stage, 
because that is the point of energy purchase by the device owner.
To simplify derivations, 
we choose not to apply final-to-primary energy multipliers
to final energy rates in the numerators and denominators of rebound expressions
derived from Eqs.~(\ref{eq:Re_def}) and~(\ref{eq:Re_takeback});
they divide out anyway.
Henceforth, we drop the adjective ``final'' 
unless there is reason to indicate a specific stage of the energy conversion chain.


%++++++++++++++++++++++++++++++
\subsection{Typical energy and cost relationships}
\label{sec:energy_and_cost_relationships}
%++++++++++++++++++++++++++++++

With the rebound notation of Appendix~\ref{sec:nomenclature}, four typical relationships emerge.
First, the consumption rate of the energy service~($\rate{q}_s$)
is the product of final-to-services efficiency~($\eta$) and
the rate of consumption of final energy by the service-producing machine~($\rate{E}_s$).
Typical units for automotive transport and illumination are provided.
**** Add illumination units. ---MKH ****
%
\begin{align} \label{eq:typ_qs_eta_Edot}
  \rate{q}_s &= \eta \rate{E}_s \\
  \text{pass-km/yr} &= [\text{pass-km/MJ}] [\text{MJ/yr}] \nonumber
\end{align}
%
Second, the energy service price~($p_s$) is the ratio of energy price~($p_E$) to the final-to-services efficiency~($\eta$).
%
\begin{align} \label{eq:ps_pE_eta}
  p_s &= \frac{p_E}{\eta} \\
  \text{\$/pass-km} &= \frac{\$/\text{MJ}}{\text{pass-km/MJ}} \nonumber
\end{align}
%
Third, cost rates~($\rate{C}$) are the product of energy price~($p_E$) and device energy consumption rates~($\rate{E}_s$).
%
\begin{align}
  \rate{C} &= p_E \rate{E}_s \\
  \text{\$/yr} &= [\text{\$/MJ}][\text{MJ/yr}] \nonumber
\end{align}
%
Fourth, energy rates~($\rate{E}$) are the product of cost rates~($\rate{C}$) and energy intensity of the economy~($I_E$).
%
\begin{align}
  \rate{E} &= \rate{C} I_E \\
  \text{MJ/yr} &= [\text{\$/yr}][\text{MJ/\$}] \nonumber
\end{align}

In the subsections that follow, 
we discuss four rebound effects, sequentially.
In each subsection, we 
%
\begin{enumerate*}[label={(\alph*)}]
	
  \item define each rebound effect and
  
  \item provide rebound expressions.
    
\end{enumerate*}
%
Detailed derivations of all rebound expressions 
can be found in Appendix~\ref{sec:derivation}.
See, in particular, Tables~\ref{tab:empleffect}--\ref{tab:prodeffect}
which provide a structure for energy and financial accounting.
We begin with the \empleffect{}.


%++++++++++++++++++++++++++++++
\subsection{\Empleffect}
\label{sec:empl_effect_main_paper}
%++++++++++++++++++++++++++++++

The emplacement effect accounts for performance of the EEU only.
No behavior changes occur.
The direct effect of emplacement of the EEU is device energy savings and energy cost savings.
The indirect effects of emplacement of the EEU are changes in the embodied energy rate and
the maintenance and disposal cost rates.

Because no behavior changes are considered,
actual and expected energy savings rates~($\Sdot$) are identical
across the direct emplacement effect, namely

\begin{equation} \label{eq:S_dot_def}
  \Sdot \equiv \rbempl{E}_s - \raempl{E}_s \; .
\end{equation}
%
Appendix~\ref{sec:Sdot} shows that

\begin{equation} \label{eq:Sdot}
  \Sdot = \Sdoteqn \; .
\end{equation}

By definition, the direct emplacement effect has no rebound, 
because actual and expected energy savings are identical.
(See Table~\ref{tab:empleffect}.)

\begin{equation} \label{eq:Re_dempl0}
  Re_{dempl} = 0
\end{equation}

On the other hand, energy rebound may be caused by indirect emplacement effects, which
account for the life cycle of the energy conversion device, including 
energy embodied by manufacturing (subscript $emb$) and
maintenance and disposal (subscript $\md$).

We define embodied energy consistent with the energy/exergy analysis literature
to be the sum of all final energy consumed (direct and indirect)
in the production of the device.
Energy is embodied in the device within manufacturing and distribution supply chains
prior to consumer acquisition of the device.
No energy is embodied in the device while in service.
The EEU
causes the embodied final energy of the device to change
from $\bempl{E}_{emb}$ to $\aempl{E}_{emb}$.

However, for simplicity, we spread all embodied energy
over the lifetime of the device,
an equal amount assigned to each period.
(We later take the same approach to capital costs and
maintenance and disposal costs.)
A justification for spreading embodied energy purchase costs comes from considering
device replacements by many consumers across several years.
In the aggregate, evenly-spaced (in time) replacements
work out to the same embodied energy in every period.

Thus, we allocate embodied energy over the life of the original and upgraded devices
($\bempl{t}_{\life}$ and $\aempl{t}_{\life}$, respectively)
to obtain embodied energy rates, such that
$\rbempl{E}_{emb} = \bempl{E}_{emb} / \bempl{t}_{\life}$
and 
$\raempl{E}_{emb} = \aempl{E}_{emb} / \aempl{t}_{\life}$.
The change in embodied final energy due to the EEU (expressed as a rate) is given by
$\raempl{E}_{emb} - \rbempl{E}_{emb}$.
The expression for embodied energy rebound is 

\begin{equation} \label{eq:Re_emb}
  Re_{emb} = \Reembeqn{} \; .
\end{equation}

Embodied energy rebound can be either positive or negative, depending on 
the sign of the term
$(\aempl{E}_{emb}/\bempl{E}_{emb})(\bempl{t}_{\life}/\aempl{t}_{\life}) - 1$.
Typically, but not always,
rising energy efficiency is associated with increased device complexity
and more embodied energy,
such that $\aempl{E}_{emb} > \bempl{E}_{emb}$ and $Re_{emb} > 0$.
However, if the upgraded device has longer life than the original device
($\aempl{t}_{\life} > \bempl{t}_{\life}$),
$\raempl{E}_{emb} - \rbempl{E}_{emb}$ can be negative,
meaning that the upgraded device has a lower embodied energy rate than the original device.
See Appendix~\ref{sec:Re_emb} for details.

In addition to embodied energy, 
indirect emplacement effect rebound accounts for
energy demanded by maintenance and disposal~($\md$) activities.
Maintenance expenditures are typically modeled as a per-year expense, a rate (e.g., $\rbempl{C}_m$).
Disposal costs (e.g., $\bempl{C}_d$) are one-time expenses incurred 
at the end of the useful life of the energy conversion device.
Like embodied energy, we spread disposal costs across the lifetime 
of the original and upgraded devices ($\bempl{t}_{\life}$ and $\aempl{t}_{\life}$, respectively)
to form cost rates such that $\rbempl{C}_{md} = \rbempl{C}_m + \bempl{C}_d/\bempl{t}_{\life}$
and
$\raempl{C}_{\md} = \raempl{C}_{m} + \aempl{C}_d/\aempl{t}_{\life}$.

For simplicity, we assume that $\md$ expenditures indicate energy consumption
elsewhere in the economy at its energy intensity~($I_E$).
Therefore, the change in energy consumption rate caused by a change in $\md$ expenditures
is given by $\Delta \raempl{C}_{\md} I_E$.
Rebound from maintenance and disposal
is given by 

\begin{equation} \label{eq:Re_md}
  Re_{\md} = \ReOMdeqn{} \; .
\end{equation}
%
See Appendix~\ref{sec:Re_OMd} for details.


%++++++++++++++++++++++++++++++
\subsection{\Subeffect}
\label{sec:sub_effect_main_paper}
%++++++++++++++++++++++++++++++

The direct rebound effect is split into substitution and
income effects, following neoclassical consumer theory. 
Neoclassical consumer theory distinguishes
substituting the energy service for
other consumption items whose relative price increases due to the 
higher efficiency and hence lower price of producing the energy 
service, and respending the higher real income. 
Because the rate of consuming other goods is altered, 
substitution and income effects affect 
both direct and indirect rebound effects.

The substitution effect alters compensated demand, which is
defined as the expenditure minimizing consumption bundle for
a given level of payoff (or utility). 
It involves
%
\begin{enumerate*}[label={(\alph*)}]

  \item an increase in consumption of the energy service,
        called direct substitution ($dsub$) indicating its relationship
        with the direct rebound effect and

  \item a compensating reduction in consumption of other goods,
        called indirect substitution ($isub$).

\end{enumerate*}
%
Thus, two terms comprise substitution effect rebound,
direct substitution rebound ($Re_{dsub}$) and
indirect substitution rebound ($Re_{isub}$).
Substitution effect rebound  
can be expressed in terms of energy service efficiencies ($\bempl{\eta}$ and $\aprod{\eta}$),
the service price elasticity of energy service consumption ($\eqsps$), and
the service price elasticity of other goods consumption ($\eqops$).

****
Add information here about elasticities.
****
See Appendix~\ref{sec:elasticities} for further details about elasticities.

The relationship between energy service price and energy service consumption rate
is given by the service price elasticity of energy service consumption~($\eqsps$),
such that

\begin{equation}
  \frac{\rasub{q}_s}{\rbsub{q}_s} = \left( \frac{\aprod{p}_s}{\bempl{p}_s} \right)^{\eqsps} \; .
\end{equation}
%
We assume that the service price elasticity of consumption is 
no greater than zero ($\eqsps < 0$)
under standard assumptions on convex preferences.
% Note that a negative value for the service price elasticity of energy service consumption 
% means that when the energy service price decreases ($\aprod{p}_s < \bempl{p}_s$),
% the rate of energy service consumption increases ($\rasub{q}_s > \rbsub{q}_s$).

Substituting the relationship of Eq.~(\ref{eq:ps_pE_eta}) in the form
$\bempl{p}_s = \frac{\bempl{p}_E}{\bempl{\eta}}$ and
$\aprod{p}_s = \frac{\bempl{p}_E}{\aprod{\eta}}$
gives

\begin{equation} \label{eq:q_ratio_func_of_eps}
  \frac{\rasub{q}_s}{\rbsub{q}_s} = \left( \etaratiostacked \right)^{-\eqsps} \; .
\end{equation}
%
Because the energy service price elasticity of energy service consumption
is negative ($\eqsps < 0$),
an energy service efficiency increase ($\aprod{\eta} > \bempl{\eta}$),
implies an energy service consumption rate increase ($\rasub{q}_s > \rbsub{q}_s$).

To quantify the \subeffect{} on other purchases,
we introduce another elasticity:
the energy service price elasticity of other goods consumption~($\eqops$).
Appendix~\ref{sec:Re_sub} shows that

\begin{equation} \label{eq:qohat_qostar}
  \frac{\rasub{q}_o}{\rbsub{q}_o} = \left( \etaratiostacked \right) ^ {-\eqops} \; .
\end{equation}
%
(See Appendix~\ref{sec:elasticities} for relationships among the elasticities.)
Because the energy service price elasticity of other goods consumption
is positive ($\eqops > 0$),
an energy service efficiency increase ($\aprod{\eta} > \bempl{\eta}$)
implies a reduction in the rate of consumption of other goods ($\rasub{q}_o > \rbsub{q}_o$).

As shown in Table~\ref{tab:subeffect}, direct substitution rebound is defined as

\begin{equation} \label{eq:Re_dsub_def}
  Re_{dsub} \equiv \frac{\Delta \rasub{E}_s}{\Sdot} \; .
\end{equation}
%
Expansion and substitution of terms (see Appendix~\ref{sec:Re_dsub})
gives

\begin{equation} \label{eq:Re_dsub}
  Re_{dsub} = \Redsubeqn{} \; .
\end{equation}

Note that the service price elasticity of energy service consumption is
expected to be negative ($\eqsps < 0$).
For example, when $\eqsps = -0.2$ and $\etaratiostacked = 2$,
$Re_{dsub} = 0.15$.

Furthermore, L'H\^{o}pital's rule can be invoked to find

\begin{equation} \label{eq:lim_Redsub_1}
  \lim_{\etaratioinline \to 1^{\!+}} Re_{dsub} = -\eqsps \; ,
\end{equation}
%
and

\begin{equation} \label{eq:lim_Redsub_infty}
  \lim_{\etaratioinline \to \infty} Re_{dsub} = 0 \; .
\end{equation}
%
With $\eqsps \in (-1, 0)$ expected,
direct substitution rebound will never be larger than 1.
Thus, the direct substitution effect alone
can never cause backfire. 

The increase in consumption of the energy service after its price drop
substitutes for consumption of other goods in the economy,
subject to the payoff constraint.
The reduction in spending on other goods in the economy
is captured by indirect substitution rebound~($Re_{isub}$).

To derive an expression for indirect substitution rebound,
we begin with the definition of $Re_{isub}$
from Table~\ref{tab:subeffect}:

\begin{equation} \label{eq:Re_isub_dev}
  Re_{isub} \equiv \frac{\Delta \rasub{C}_o I_E}{\Sdot} \; .
\end{equation}

We assume a basket of other goods purchased in the economy,
each ($i$) with its own price ($p_{o,i}$) and rate of consumption ($\rate{q}_{o,i}$).
We further assume that the average price is unchanged across the substitution effect,
such that $\asub{p}_o = \bsub{p}_o$.
After substitution and rearrangement (see Appendix~\ref{sec:Re_isub}),
we find

\begin{equation} \label{eq:Re_isub}
  Re_{isub} = \Reisubeqn{} \; .
\end{equation}

Because the service price elasticity of other goods consumption is positive ($\eqops > 0$) and
the energy service efficiency ratio is greater than 1 ($\aprod{\eta} > \bempl{\eta}$),
indirect substitution rebound will be negative always ($Re_{isub} < 0$),
as expected.
Negative rebound indicates that indirect substitution reduces the energy takeback by direct substitution.

Invoking L'H\^{o}pital's rule gives

\begin{equation} \label{eq:lim_Reisub_1}
  \lim_{\etaratioinline \to 1^{\!+}} Re_{isub} 
        = -\eqops \frac{\rbempl{C}_o I_E}{\rbempl{E}_s} \; ,
\end{equation}
%
and

\begin{equation} \label{eq:lim_Reisub_infty}
  \lim_{\etaratioinline \to \infty} Re_{isub} = - \frac{\rbempl{C}_0 I_E}{\rbempl{E}_s} \; .
\end{equation}


%++++++++++++++++++++++++++++++
\subsection{\Inceffect}
\label{sec:inc_effect_main_paper}
%++++++++++++++++++++++++++++++

Rebound from the \inceffect{} quantifies the rate of additional energy demand 
that arises when the energy conversion device owner spends net
income from the EEU.
The income rate of the device owner is $\rbempl{M}$, 
which remains unchanged across the rebound effects, 
such that
$\rbempl{M} = \raempl{M} = \rasub{M} = \rainc{M} = \raprod{M}$.
Gross income from the EEU is given by Eq.~(\ref{eq:G_dot})
as $\rate{G} = p_E \Sdot$. 
In combination, the \empleffect{} and the \subeffect{} leave the device owner with
\emph{net} income ($\rasub{N}$) from the EEU,
as shown in Eq.~(\ref{eq:N_dot_after_sub}).
Derivations of expressions for gross and net income from the 
\empleffect{} ($\rate{G}$) and the \subeffect{} ($\rasub{N}$)
are presented in Tables~\ref{tab:empleffect} and~\ref{tab:subeffect}.

In this framework, all net income ($\rasub{N}$) is spent either 
%
\begin{enumerate*}[label={(\alph*)}]
	
  \item on additional energy service ($\rainc{q}_s > \rbinc{q}_s$) or
  
  \item on additional other goods ($\rainc{q}_o > \rbinc{q}_o$).
    
\end{enumerate*}
%
The income elasticity of energy service consumption ($\eqsM$)
quantifies the amount of net income spent 
on more of the energy service ($\rainc{q}_s > \rbinc{q}_s$).
(See Appendix~\ref{sec:elasticities} for additional information about elasticities.)

The ratio of rates of energy service consumed across the income effect is given by

\begin{equation} \label{eq:qsrat_eqsM}
  \incprefseqn \; ,
\end{equation}
%
where effective income ($\Mdothatprime$) is given by 

\begin{equation} \label{eq:effective_income}
  \effinceqn{} \; .
\end{equation}
%
Homotheticity means that $\eqsM = 1$ and $\eqoM = 1$.

As shown in Table~\ref{tab:inceffect}, direct income rebound is defined as

\begin{equation} \label{eq:Re_dinc_def}
  Re_{dinc} \equiv \frac{\Delta \rainc{E}_s}{\Sdot} \; .
\end{equation}
%
After much substitution, rearranging, and canceling of terms (see Appendix~\ref{sec:Re_dinc}), 
the expression for direct income rebound is

\begin{equation} \label{eq:Re_dinc}
  Re_{dinc} = \Redinceqn{} \; .
\end{equation}

If there is no net income ($\rasub{N} = 0$), 
direct income effect rebound is zero ($Re_{dinc} = 0$), as expected.
As either of the elasticities gets stronger 
($\eqsM$ becomes more positive or $\eqsps$ becomes more negative), 
direct income rebound~($Re_{dinc}$) grows.

The income elasticity of other goods consumption ($\eqoM$)
quantifies the amount of net income spent 
on additional other goods ($\rainc{q}_o > \rbinc{q}_o$).
(See Appendix~\ref{sec:elasticities} for additional information about elasticities.)

The ratio of rates of other goods consumed across the income effect is given by

\begin{equation} \label{eq:qorat_eqoM}
  \incprefoeqn \; .
\end{equation}
%
As shown in Table~\ref{tab:inceffect}, indirect income rebound is defined as

\begin{equation} \label{eq:Re_iinc_def}
  Re_{iinc} \equiv \frac{\Delta \rainc{C}_o I_E}{\Sdot} \; .
\end{equation}
%
After much substitution, rearranging, and canceling of terms (see Appendix~\ref{sec:Re_iinc}), 
the expression for indirect income rebound is

\begin{equation} \label{eq:Re_iinc}
  Re_{iinc} = \Reiinceqn{} \; .
\end{equation}

In the midst of the \inceffect{} analysis, a capital expenses rebound term appears:

\begin{equation} \label{eq:Re_cap}
  Re_{cap} = \Recapeqn{} \; .
\end{equation}

% Positive rebound from capital expenditures~($Re_{cap}$), 
% maintenance and disposal~($Re_{\md}$),
% direct substitution~($Re_{dsub}$), 
% indirect substitution~($Re_{isub}$), and 
% direct income~($Re_{dinc}$)
% reduce the indirect income effect rebound, 
% because each reduces net monetary savings available to the device owner to spend on other goods in the economy.
% Any negative rebound effects enhance the indirect income effect rebound, because 
% they add to the net monetary savings available to the device owner to spend on other goods in the economy.

The income preferences expressions (Eqs.~(\ref{eq:qsrat_eqsM}) and ~(\ref{eq:qorat_eqoM}))
must satisfy the budget constraint
such that net income is zero after
the \inceffect{} ($\rainc{N} = 0$).
See Appendix~\ref{sec:proof_income_elasticities}
for a proof demonstrating that the income preference equations satisfies the budget constraint.

+++
Should we add a subsection here on `economy-wide effects',
that is changes in prices, including a lower energy price,
so we get the `price effect'?---GS
+++


%++++++++++++++++++++++++++++++
\subsection{\Prodeffect}
\label{sec:prod_effect_main_paper}
%++++++++++++++++++++++++++++++

The previous rebound effects
(\empleffect{}, \subeffect{}, and \inceffect{})
are microeconomic in nature.
**** Revisit this statement after we finalize our topology.---MKH ****
In contrast, the productivity effect is macroeconomic.
%At the macro level, we claim that the effect of energy efficiency is expansionary,
%just like other factor-augmenting productivity improvements.
%This argument implicitly assumes two things:
%
%\begin{enumerate*}[label={(\alph*)}]

%  \item that, together with capital and labor, energy is a factor of production, and

%  \item energy efficiency operates along the supply side by reducing the cost of inputs
%        (in this case, final energy),
%        thereby allowing production on a greater scale.

%\end{enumerate*}
Like other factor-augmenting technical change, energy-augmenting
technical change reduces production costs and thereby enables more efficient
production (process innovation) that typically results in growth.
Additionally, cheaper energy services could facilitate the
development and deployment of new products (product innovation),
an important driver of rising aggregate demand (Szostack 1995)
**** This references needs to go into BibTeX ****.
The upshot is that while energy efficiency is higher, the more 
efficient economy is growing more than one without the improvement,
taking back part of the expected energy savings. We call this the
productivity effect.
+++
If we follow my argument that there is only one growth effect,
we could also call it growth effect, which is more intuitive
---GS
+++

In general, reducing cost of inputs at the micro level can lead
to important and surprising counter-tendencies in factor consumption at the macro level.
Consider labor productivity: it has risen 20-fold
in Western Europe and the US since 1820 \citep{Maddison:2001aa}, and
yet today these countries employ more workers than ever before.
**** Can we also include examples of other inputs,
while avoiding the capital controversy?
Doing so would round out the illustrations and really drive home the point. 
Does \citet{Magee2017} help with this?---MKH ****
Consider XXXXXX: it has risen YY-fold,
yet more XXXXXX is in service than ever before. **** Need statistics here. ---MKH ****
And so too with energy.
While energy efficiency at the device-level has climbed in the past century,
energy consumption at the macro level has also risen.
\citet{Heun:2019aa} **** Heun et al.\ are not the best reference here.
Can PB provide an alternative? ****
show that increases in energy efficiency at the micro level
go hand-in-hand with 
increases in overall energy consumption at the macro level.
It is important to recognise the generality of this result.
Typically focus is less interested in overall savings of an input,
but once expected savings are of interest, all factor-augmenting
technical change that accelerates economic growth can be analyzed
in terms of its contribution to rebound relative to counterfactual
scenario of lower growth.
%Of course, this generality between energy on the one hand
%and other inputs (XXXXX and labor) on the other hand
%raises the question whether it is appropriate to speak of a rebound effect at all.
%Isn't all technological progress just a rebound effect?
%We put it the opposite way:
%macroeconomic rebound effects are the consequences of technological change,
%whether
%in utilization of XXXXXX,
%in utilization of labor, or
%in utilization of energy.

Further, we claim that productivity effect rebound stems from technological improvements
(energy efficiency)
which can be correlated to energy service price reductions.
As such, productivity effect rebound at the macro level scales with the net income~($\rasub{N}$)
gained by device owners at the micro level.
As shown by \citet{Antal:2014aa},
it is reasonable to assume that
net income ($\rasub{N}$) is spent in the economy at the average energy intensity of the economy ($I_E$).

Scaling from net income ($\rasub{N}$) at the device level
to productivity-driven growth at the macro level is an unexplored area.
In the absence of better information,
we express this scaling simply by a productivity factor ($k$)
with $k \ge 0$ expected.
$k = 0$ means two things:
%
\begin{enumerate*}[label={(\alph*)}]

  \item the device owner's freed cash is simply redistributed to a new basket of goods
        with no energy implications and

  \item there is no macroeconomic productivity boost that results from the energy efficiency upgrade.

\end{enumerate*}
%
$k > 0$ means that productivity-driven macroeconomic growth has occurred
with consequent implications for additional energy consumption at the macro level.
This should not be confused with a ``multiplier" from Keynesian economics,
on which more in the discussion.

As shown in Table~\ref{tab:prodeffect}, 
productivity rebound is given by

\begin{equation} \label{eq:Re_prod_def}
  Re_{\productivity} = \frac{k \rbinc{N} I_E}{\Sdot} \; .
\end{equation}
%
After some algebra (see Appendix~\ref{sec:Re_prod}), 
we arrive at an expression for \prodeffectadj{} rebound:

\begin{equation} \label{eq:Re_prod}
  Re_{\productivity} = \Reprodeqn{} \; .
\end{equation}
%

%++++++++++++++++++++++++++++++
\subsection{Rebound sum}
\label{sec:total_rebound_main_paper}
%++++++++++++++++++++++++++++++

In the comprehensive framework,
the sum of all rebound emerges from the four rebound effects
(\empleffect{}, \subeffect{}, \inceffect{}, and \prodeffect{}).
Productivity effect rebound~($Re_{\productivity}$, Eq.~(\ref{eq:Re_prod}))
is expressed in terms of other rebound effects.
(Derivation details can be found in Appendix~\ref{sec:total_rebound}.)
After algebra and canceling of terms,
we find
%
\begin{align} \label{eq:Re_tot}  
  Re_{sum} = \; \Retoteqn{} \; .
\end{align}


<<eeu_data, echo=FALSE>>=
# Load our test cases and perform rebound analyses.
rebound_data <- ReboundTools::load_eeu_data("data/eeu_data.xlsx")
rebound_results <- ReboundTools::rebound_analysis(rebound_data)
@


**** Show an example set of graphs here? ****




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Calculations: two examples (PB, 2000 words)}
\label{sec:examples}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

To demonstrate application of the 
rebound analysis framework developed in Section~\ref{sec:framework},
we select two case studies:
energy efficiency upgrades for an automobile and an electric lamp.
We first collect parameter values
for the equations for
eight rebound components:
$Re_{dempl}$ (Eq.~(\ref{eq:Re_dempl0})),
$Re_{emb}$ (Eq.~(\ref{eq:Re_emb})),
$Re_{\md}$ (Eq.~(\ref{eq:Re_md})),
$Re_{dsub}$ (Eq.~(\ref{eq:Re_dsub})),
$Re_{isub}$ (Eq.~(\ref{eq:Re_isub})),
$Re_{dinc}$ (Eq.~(\ref{eq:Re_dinc})),
$Re_{iinc}$ (Eq.~(\ref{eq:Re_iinc})), and
$Re_{\productivity}$ (Eq.~(\ref{eq:Re_prod})).
The total rebound sum ($Re_{sum}$)
is given by the sum of the above components,
which can also be checked against Eq.~(\ref{eq:Re_tot}).
 

%++++++++++++++++++++++++++++++
\subsection{Case 1: Automobile}
\label{sec:Car_example}
%++++++++++++++++++++++++++++++

For the first example, 
we select the purchase of a more fuel efficient car (Ford Fusion Energi), 
versus the incumbent (Ford Fusion SE). 
The cars are matched as closely as possible, 
except for the inclusion of an electric battery 
in the gas-electric hybrid Energi car.  
The automobile case study has a very high 
initial capital investment
and a long-term benefit of decreased direct energy costs. 


%------------------------------
\subsubsection{Input parameters} 
\label{sec:Car_input_data}
%------------------------------

We require four sets of data. 
First, the basic car parameters, which are summarized 
in Table~\ref{tab:car_parameters}.

% Reduce spacing between table rows henceforth.
\renewcommand{\arraystretch}{0.6}

\begin{landscape}
\begin{table}
\begin{center}
\caption{Car example: Vehicle parameters.} 
\label{tab:car_parameters}
\begin{tabular}{ r c c l }
  \toprule
    Description                  & Ford Fusion & Ford Fusion & Data sources and notes\\ 
    Parameters [units]                                & (gasoline) & (hybrid EV) &  \\
  \midrule
  Fuel efficiency                                   & 25        & 42       & Combined cycle mpg value taken from \citet{Car_Connection:2020}, \\
  $\bempl{\eta}$, $\aprod{\eta}$ [mpg]              &           &          & Turbo Premium Unleaded for Titanium FWD model with Intercooled  \\
                                                    &           &          & I-4, 2.0 L engine. \\
                                                    &           &          & Combined cycle mpg value taken from \citet{Car_Connection:2020},\\
                                                    &           &          & for Titanium FWD model with Gas/Electric I-4, 2.0 L engine. \\
  \midrule
   Capital cost rate                                & 4,031     & 3,932    & Seven year annual, averaged capital costs = purchase + finance costs \\
   $\rbempl{C}_{cap}$, $\raempl{C}_{cap}$ [\$/year] &           &          & -- resale value (purchase -- depreciation). Fusion gasoline costs from \\
                                                    &           &          & \citet{Edmunds:2019_gasoline_fusion}. Fusion Energi car costs from \citet{Edmunds:2019_energi_fusion}. \\
 \midrule
   Ownership duration                               & 7         & 7        & US car ownership (from new) length taken from \citet{BusinessWire:2015}, \\
   $\bempl{t}_{own}$, $\aempl{t}_{own}$ [years]     &           &          & and has risen from 52 months (2005) to 79 months (2015), so assumed as \\
                                                    &           &          & 84 months in 2019 (7 years) for our example. \\
 \midrule
   Lifespan                                         & 14        & 14       & Lifetime taken as 14 years, based on 13--17 years for US cars \\
   $\bempl{t}_{\life}$, $\aempl{t}_{\life}$ [years] &           &          & from \citet{Berla:2016} and 14 years for UK cars from \\
                                                    &           &          & \citet{SMMT:2020}. \\
   \midrule
   Embodied energy rate                             & 34,000    & 40,000   & 34,000 MJ for gasoline car taken from \\
   $\bempl{E}_{emb}$, $\aempl{E}_{emb}$ [MJ]        &           &          & \citet{Argonne_National_Laboratory:2010}. \\
                                                    &           &          & We assume an additional 6,000 MJ added for Hybrid Electric Vehicle (HEV) \\
                                                    &           &          & battery, as HEV typically 10--25\% of total LCA energy of vehicle  \\
                                                    &           &          & manufacture. Battery lifetime assumed same as car lifetime, based on \\
                                                    &           &          & \citet{nordelof2014environmental}, and \citet{onat2015conventional}. \\
 \midrule
  Maintenance and disposal cost rate                & 2,861     & 2,775    & Seven year annual, averaged maintenance costs = sum of insurance, \\
  $\rbempl{C}_{\md}$, $\raempl{C}_{\md}$ [\$/year]  &           &          & maintenance, repairs, taxes, and fees (excluding financing, depreciation, fuel). \\
                                                    &           &          & Fusion gasoline car maintenance costs from \citet{Edmunds:2019_gasoline_fusion}. \\
                                                    &           &          & Fusion Energi maintenance costs from \citet{Edmunds:2019_energi_fusion}. \\
  \bottomrule
\end{tabular}
\end{center}
\end{table}
\end{landscape}

Second, we require several general parameters, 
mainly relating to the US economy and personal finances 
of the average US citizen. 
The parameters and their values used in the study 
are given in Table~\ref{tab:car_economic_parameters}.

\begin{landscape}
\begin{table}
\begin{center}
\caption{Car example: Economic parameters}
\label{tab:car_economic_parameters}
\begin{tabular}{ r c l }
  \toprule
  Description & Value & Data sources and notes \\ 
  Parameter [units] & & \\
  \midrule
  Distance driven prior to upgrade                          & 14,425        & Average US vehicle miles/year, taken from \citet{Car_Insurance:2019}.  \\
  $\rbempl{q}_s$ [miles/year]                               &               & This is slightly higher than the average driver miles/year (13,476) from \\
                                                            &               & \citet{US_DoT:2018}. \\
  \midrule
  Real median personal income US, in 2018                   & 33,706        & Taken from \citet{St_Louis_Fed:2019}.\\
  {} [\$/year]                                              &               & \\
  \midrule
  US Disposable income /                                    & 0.88268       & Taken from US Bureau of Economic Analysis (BEA) \\
  real income (minus current taxes)                         &               & National and Products Accounts (NIPA) \\
  {} [--]                                                   &               & Table 2.1. Personal Income and Its Disposition, \\
                                                            &               & \citet{US_BEA:2020}, \\ 
  \midrule
  Share of savings from disposable income                   & 0.079         & Taken from US Bureau of Economic Analysis (BEA) \\
  {} [--]                                                   &               & National and Products Accounts (NIPA) \\ 
                                                            &               & Table 2.1. Personal Income and Its Disposition, \\
                                                            &               & \citet{US_BEA:2020}, \\
  \midrule
  Personal consumption                                      & 27401.28      & Calculation: $(\$33,706\mathrm{/year}) (0.88268) (1 - 0.079)$ \\
  $\rate{M}$ [\$/year]                                      &               &                                              \\
  \midrule
  Price of gasoline                                         & 2.21          & Taken from US Energy Information Agency (EIA) data \\
  $p_E$ [\$/gallon]                                         &               & \citet{US_EIA:2020_gasoline} \\
  \midrule  
  Fractional spend on energy service                        & 0.062         & Calculation: \$1,275 (spend on energy service) \\
  $\fCs$ [--]                                               &               & / [\$19,234 (spend on other goods) + \\
                                                            &               & \$1,275 (spend on energy service)] = 0.062, \\
                                                            &               & where spend on energy service = 14,425 miles / 42 mpg \\
                                                            &               & $\times$ \$2.21/gallon = \$1,275. \\
  \midrule
  Productivity multiplier                                   & 1.0           & Assumed value \\  
  $k$ [--]                                                  &               &               \\
  \bottomrule
\end{tabular}
\end{center}
\end{table}
\end{landscape}

Third, we require elasticity parameters, 
as given in Table~\ref{tab:car_elasticity_parameters}.

\begin{landscape}
\begin{table}
\begin{center}
\caption{Car example: Elasticity parameters}
\label{tab:car_elasticity_parameters}
\begin{tabular}{ r c l }
  \toprule
  Description & Value & Data sources and notes \\
  Parameter [units] & & \\
  \midrule
  Marshallian (uncompensated) price elasticity of demand  &   -0.1    & Source: \citet{Borenstein:2015aa}. \\
  $\eqspsUC$ [--]                                         &           &   \\ 
  \midrule
  Price elasticity of demand for car use                  &   -0.077  & Calculated via the Slutsky Equation (Eq.~\ref{eq:slutsky}).  \\
  $\eqsps$ [--]                                           &           &   \\    
  \midrule   
  Cross price elasticity of demand for other goods        &   0.002   & Calculated via Eq.~\ref{eq:eqops}.  \\
  $\eqops$ [--]                                           &           &   \\ 
  \midrule   
  Income elasticity of demand for car use                 &   1.0     & Assumed value. \\
  $\eqsM$ [--]                                            &           &   \\ 
  \midrule   
  Income elasticity of demand for other goods             &   1.0     & Assumed value. \\
  $\eqoM$ [--]                                            &           &   \\
  \bottomrule
\end{tabular}
\end{center}
\end{table}
\end{landscape}

Fourth, armed with the parameter values from 
Tables~\ref{tab:car_parameters}--\ref{tab:car_elasticity_parameters}, 
and the equations of Section~\ref{sec:framework},
we calculate important values at each rebound stage,
as shown below in Table~\ref{tab:car_stages_table}.

<<car_stages_table, results="asis", echo=FALSE>>=
digs_car <- matrix(c(rep(1, 7), # eta_engr_units
                     rep(3, 7), # eta
                     rep(3, 7), # p_s
                     rep(0, 7), # q_dot_s
                     rep(0, 7), # E_dot_s
                     rep(0, 7), # E_dot_emb
                     rep(0, 7), # C_dot_s
                     rep(0, 7), # C_dot_cap
                     rep(0, 7), # C_dot_md
                     rep(0, 7), # C_dot_o
                     rep(0, 7), # N_dot
                     rep(0, 7)), # M_dot
                   nrow = 12, ncol = 7, byrow = TRUE)
rebound_results %>% 
  dplyr::filter(Case == "Car") %>% 
  dplyr::mutate(
    Case = NULL
  ) %>% 
  ReboundTools::stages_table(label = "tab:car_stages_table", 
                             caption = "Results for car example.", 
                             digits = digs_car, 
                             align = "lrrrrrr") %>% 
  print(include.rownames = FALSE, 
        booktabs = TRUE,
        caption.placement = "top",
        sanitize.text.function = function(x) {x},
        format.args = list(big.mark = ","))
@


%------------------------------
\subsubsection{Results} 
\label{sec:Car_results}
%------------------------------

The base results for the automobile upgrade are shown in Table~\ref{tab:car_results}.

<<car_rebound_results_table, results="asis", echo=FALSE>>=
rebound_results %>% 
  dplyr::filter(Case == "Car") %>% 
  dplyr::mutate(
    Case = NULL
  ) %>% 
  ReboundTools::rebound_results_table(include_subtotals = FALSE, 
                                      label = "tab:car_results", 
                                      caption = "Car example: rebound results.", 
                                      digits = 1, 
                                      align = "rrr") %>% 
  print(include.rownames = FALSE, 
        booktabs = TRUE,
        caption.placement = "top",
        hline.after = c(-1, 0, nrow(.)-1, nrow(.)),
        sanitize.text.function = function(x) {x},
        format.args = list(big.mark = ","))
@




% \begin{table}
% \begin{center}
% \caption{Car example: rebound results}
% \label{tab:car_results_old}
% \begin{tabular}{ r r }
%   \toprule
%   Rebound effect (symbol) & Value [\%] \\ 
%   \midrule
%   Emplacement effect--direct ($Re_{dempl}$) & 0.0 \\
%   Embodied energy effect--indirect ($Re_{emb}$) & 1.4 \\ 
%   Maintenance and disposal effect--indirect ($Re_{md}$) & --1.0 \\ 
%   Substitution effect--direct ($Re_{dsub}$) & 2.9 \\ 
%   Substitution effect--indirect ($Re_{isub}$) & --0.3 \\ 
%   Income effect--direct ($Re_{dinc}$) & 5.3 \\ 
%   Income effect--indirect ($Re_{iinc}$) & 7.8 \\ 
%   Macroeconomic productivity effect--indirect ($Re_{prod}$) & 8.2 \\   
%   \midrule
%   Total ($Re_{sum}$) & 24.4 \\
% \bottomrule
% \end{tabular}
% \end{center}
% \end{table}


<<CarGraphParams, echo=FALSE>>=
pal <- RColorBrewer::brewer.pal(12, "Paired")
car_graph_params <- ReboundTools::default_graph_params
car_graph_params$dempl_colour <- "lightgray"
car_graph_params$dempl_size <- 0.5
car_graph_params$dempl_linetype <- "longdash"
car_graph_params$emb_colour <- pal[[1]]
car_graph_params$cap_colour <- pal[[1]]
car_graph_params$md_colour <- pal[[2]]
car_graph_params$md_size <- 0.3
car_graph_params$md_linetype <- "dotted"
car_graph_params$dsub_colour <- pal[[3]]
car_graph_params$dsub_size <- 0.3
car_graph_params$dsub_linetype <- "dashed"
car_graph_params$isub_colour <- pal[[4]]
car_graph_params$dinc_colour <- pal[[5]]
car_graph_params$dinc_size <- 0.3
car_graph_params$dinc_linetype <- "dashed"
car_graph_params$iinc_colour <- pal[[6]]
car_graph_params$prod_colour <- pal[[7]]
@

<<CarEnergyGraph, echo=FALSE, fig.cap="Energy path graph, car example.", fig.width=6, fig.height=4>>=
rebound_data %>% 
  rebound_analysis() %>% 
  ReboundTools::rebound_graphs(cases = "Car", 
                               graph_types = "Energy", 
                               graph_params = car_graph_params) + 
  MKHthemes::xy_theme()
@


<<CarCostGraph, echo=FALSE, fig.cap="Cost path graph, car example.", fig.width=6, fig.height=4>>=
rebound_data %>% 
  rebound_analysis() %>% 
  ReboundTools::rebound_graphs(cases = "Car", 
                               graph_types = "Cost", 
                               graph_params = car_graph_params) + 
  MKHthemes::xy_theme()
@


<<CarPrefsGraph, echo=FALSE, fig.cap="Preferences path graph, car example.", fig.width=6, fig.height=4>>=
car_graph_params$prefs_indiff_grid_size <- 1
car_graph_params$n_indiff_curve_points <- 10
car_graph_params$qs_qs0_lower <- 0.9
car_graph_params$qs_qs0_upper <- 1.2

rebound_data %>% 
  rebound_analysis() %>% 
  ReboundTools::rebound_graphs(cases = "Car", 
                               graph_types = "Preferences", 
                               graph_params = car_graph_params) + 
  ggplot2::xlim(0.95, 1.1) +
  ggplot2::ylim(NA, 1.04) +
  MKHthemes::xy_theme()
@



Let's take each of these effects in turn. 
First, is the \empleffect, which is in three parts:
the direct emplacement effect = 0\%; 
the embodied energy effect, which is positive (+1.4\%), 
due to the higher embodied energy (+6,000MJ) 
stemming from the electric battery in the hybrid EV car; 
and the maintenance and disposal effect (-1.0\%), 
which is low and negative  
because of the slightly lower maintenance and disposal costs
in the hybrid EV car. 
Second, is the \subeffect, 
which splits into two components 
at the original income level. 
The direct substitution effect yields +2.9\% value,
which is expected, as the new fuel efficiency (42 mpg) 
is much higher than the baseline car (25 mpg), 
leading to a preference to switch more spending to more driving. 
In other words, with no other changes, 
the more fuel efficient car increases the amount of miles driven by 2.9\%. 
Conversely, the indirect substitution effect yields a value of -0.3\%, 
being slightly negative as the increased fuel use 
and miles driven in the direct substitution effect 
means that less is spent on other goods.  

Third, is the \inceffect, 
where the car 
user sees an increase in their ‘effective’ income
due to a net saving in outgoings associated with the car purchase and use, 
this effect also splits into two. 
One is the direct income effect (+5.3\%), 
which is positive and non-zero as the car user allocates some
of the additional income to driving further still. 
The indirect income effect is also positive (+7.8\%), 
due to higher spend on other sectors. 
So, the additional ``effective'' income 
($\rasub{N} = 712$ \$/year) 
translates into direct and indirect income effects at the micro-level. 
Last, is the macroeconomic 
\prodeffect (+8.2\%), 
due to the larger economy that now exists, 
so the additional money spent in the economy 
has a positive rebound multiplier effect.


%++++++++++++++++++++++++++++++
\subsection{Case 2: Electric lamp}
\label{sec:lamp_example}
%++++++++++++++++++++++++++++++

For our second example, 
we select the option of buying a light emitting diode (LED) electric lamp, 
versus a baseline incandescent electric lamp. 
Both lamps are matched as closely as possible 
in terms of energy service delivery (lumens), 
the key difference is in the energy required to provide that energy service. 
The electric lap case study has a very low 
initial capital investment (negative, actually!)
and a long-term benefit of decreased direct energy costs.


%------------------------------
\subsubsection{Input data} 
\label{sec:lamp_input_data}
%------------------------------

Again, we require four sets of data. 
First, the basic lamp parameters, which are summarized below:  
Table~\ref{tab:lamp_parameters} shows parameters for the electric lamp efficiency upgrade (EEU).

\begin{landscape}
\begin{table}
\begin{center}
\caption{Lamp example: Electric lamp parameters.} 
\label{tab:lamp_parameters}
\begin{tabular}{ r c c l }
  \toprule
    Description                  & Incandescent lamp & LED lamp & Data sources and notes\\ 
    Parameters [units]                                &  &  & \\
  \midrule
  Lamp efficacy                                     & 8.83      & 81.8     & Incandescent: 530 lm output / 60 W energy input. \\
  $\bempl{\eta}$, $\aprod{\eta}$ [lm-hr/W-hr]       &           &          & LED: 450 lm output / 5.5 W energy input. \\
  \midrule
   Capital cost rate                                & 1.044     & 0.121    & Purchase costs: \$1.88 for incandescent lamp from  \\
   $\rbempl{C}_{cap}$, $\raempl{C}_{cap}$ [\$/year] &           &          & \citet{Home_Depot:2020_Inc_bulb}, \\
                                                    &           &          & and \$1.21 for LED lamp from \\
                                                    &           &          & \citet{Home_Depot:2020_LED_bulb}. \\
  \midrule
   Ownership duration                               & 1.8       & 10       & Assumed same as lamp lifespan \\
   $\bempl{t}_{own}$, $\aempl{t}_{own}$ [years]     &           &          &  \\
 \midrule
   Lifespan                                         & 1.8       & 10       & Based on assumed 3 hours/day  \\
   $\bempl{t}_{\life}$, $\aempl{t}_{\life}$ [years] &           &          & from \citet{Home_Depot:2020_Inc_bulb} \\
                                                    &           &          & and  \citet{Home_Depot:2020_LED_bulb}. \\
   \midrule
   Life cycle analysis (LCA) embodied energy        & 2.21      & 6.50     & Base document: Table 4.5 Manufacturing Energy  \\
   $\bempl{E}_{emb}$, $\aempl{E}_{emb}$ [MJ]        &           &          & Primary energy (MJ/20 Million lumen hours), \\
                                                    &           &          & US DoE Life-cycle assessment of energy and environmental \\
                                                    &           &          & impacts of LED lighting products \\
                                                    &           &          & \citep{US_DoE:2012}. \\
                                                    &           &          & Incandescent: \\
                                                    &           &          & LCA energy = 42.2 MJ/20 million lumen-hours.  \\
                                                    &           &          & Lifetime output = 530 lumens $\times$ 3 hours/day \\
                                                    &           &          & $\times$ 365 days/year $\times$ 1.8 years = 1,044,630 lumen-hrs.\\
                                                    &           &          & Thus LCA energy / lamp =  42.2 $\times$ 1.0446/20 = 2.21 MJ. \\
                                                    &           &          & LED:  \\
                                                    &           &          & LCA energy = 132 MJ/20 Million lumen-hours for pack of 5 LED lamps. \\
                                                    &           &          & Lifetime output = 450 lumens $\times$ 3 hours/day  \\
                                                    &           &          & $\times$ 365 days/year $\times$ 10 years = 4,926,405 lumen-hrs. \\
                                                    &           &          & Thus LCA energy / lamp =  132 MJ/5 $\times$ 4.9264/20 = 6.5 MJ. \\ 
 \midrule
  Maintenance and disposal cost rate                & 0.00      & 0.00     & Assumed negligible. \\
  $\rbempl{C}_{\md}$, $\raempl{C}_{\md}$ [\$/year]  &           &          & \\
  \bottomrule
\end{tabular}
\end{center}
\end{table}
\end{landscape}




Second, we require several general parameters, 
mainly relating to the US economy and 
personal finances of the average US citizen. 
The parameters and their values used in the study 
are given below in Table~\ref{tab:lamp_economic_parameters}.

\begin{landscape}
\begin{table}
\begin{center}
\caption{Lamp example: Economic parameters}
\label{tab:lamp_economic_parameters}
\begin{tabular}{ r c l }
  \toprule
  Description  & Value & Data sources and notes \\ 
  Parameter [units] & & \\
  \midrule
  Lighting consumption prior to upgrade                     & 580,350       & Calculation: 530 lm $\times$ 3 hrs/day $\times$ 365 days/year. \\
  $\rbempl{q}_s$ [lm-hr/year]                               &               & \\
  \midrule
  Real median personal income US, in 2018                   & 33,706        & Source: \citet{St_Louis_Fed:2019}.\\
  {} [\$/year]                                              &               & \\
  \midrule
  US Disposable income /                                    & 0.88268       & Source:  National and Products Accounts (NIPA) \\
  real income (minus current taxes)                         &               & Table 2.1. Personal Income and Its Disposition \\
  {} [--]                                                   &               & \citep{US_BEA:2020}. \\
  \midrule
  Share of savings from disposable income                   & 0.079         & Source: National and Products Accounts (NIPA) \\
  {} [--]                                                   &               & Table 2.1. Personal Income and Its Disposition \\ 
                                                            &               & \citep{US_BEA:2020}. \\
  \midrule
  Personal consumption                                      & 27,401.28     & Calculation: $(\$33,706\mathrm{/year}) (0.88268) (1 - 0.079)$. \\
  $\rate{M}$ [\$/year]                                      &               &                                              \\
  \midrule
  Price of electricity                                      & 0.0227        & US 2020 average household electricity price: \$0.1355/kW-hr \\
  $p_E$ [\$/MJ]                                             &               & \citep{US_EIA:2020_electricity}.  \\
                                                            &               & Calculation: \$0.1355/kW-hr / 3.6 MJ/kW-hr = \$0.0227/MJ. \\
  \midrule
  Fractional spend on energy service                        & 0.00032       & Calculation: \$9/year (spend on energy service) / \\
  $\fCs$ [--]                                               &               & [\$27,391/year (spend on other goods) + \\
                                                            &               & \$9/year (spend on energy service)] = 0.00032, \\
                                                            &               & where spend on energy service = 580,350 lm-hrs/year /  \\
                                                            &               & 81.8 lm/W / 1000 W/kW $\times$ \$0.1355/kW-hr = \$9/year.  \\
  \midrule
  Productivity multiplier                                   & 1.0           & Assumed value. \\  
  $k$ [--]                                                  &               &               \\
  \bottomrule
\end{tabular}
\end{center}
\end{table}
\end{landscape}


Third, we require the elasticity parameters that we shall need, 
as given in Table~\ref{tab:lamp_elasticity_parameters}.

\begin{landscape}
\begin{table}
\begin{center}
\caption{Lamp example: Elasticity parameters}
\label{tab:lamp_elasticity_parameters}
\begin{tabular}{ r c l }
  \toprule
  Description & Value & Data sources and notes \\
  Parameter [units] & & \\
  \midrule
  Marshallian (uncompensated) price elasticity of demand  &   -0.4    & Source: \citet{Borenstein:2015aa}. **** Need lamp ref. **** \\
  $\eqspsUC$ [--]                                         &           &   \\ 
  \midrule
  Price elasticity of demand for car use                  &   -0.3997  & Calculated via the Slutsky Equation (Eq.~\ref{eq:slutsky}).  \\
  $\eqsps$ [--]                                           &           &   \\    
  \midrule   
  Cross price elasticity of demand for other goods        &   0.0001   & Calculated via Eq.~\ref{eq:eqops}.  \\
  $\eqops$ [--]                                           &           &   \\ 
  \midrule   
  Income elasticity of demand for car use                 &   1.0     & Assumed value. \\
  $\eqsM$ [--]                                            &           &   \\ 
  \midrule   
  Income elasticity of demand for other goods             &   1.0     & Assumed value. \\
  $\eqoM$ [--]                                            &           &   \\
  \bottomrule
\end{tabular}
\end{center}
\end{table}
\end{landscape}

Fourth, with the parameter values from 
Tables~\ref{tab:lamp_parameters}--\ref{tab:lamp_elasticity_parameters} 
and the equations of Section~\ref{sec:framework} in hand,
we calculate important values at each rebound stage,
as shown below in Table~\ref{tab:lamp_stages_table}.

<<lamp_stages_table, results="asis", echo=FALSE>>=
digs_lamp <- matrix(c(rep(0, 7), # eta_engr_units
                      rep(0, 7), # eta
                      rep(8, 7), # p_s
                      rep(0, 7), # q_dot_s
                      rep(1, 7), # E_dot_s
                      rep(3, 7), # E_dot_emb
                      rep(2, 7), # C_dot_s
                      rep(2, 7), # C_dot_cap
                      rep(2, 7), # C_dot_md
                      rep(0, 7), # C_dot_o
                      rep(2, 7), # N_dot
                      rep(0, 7)), # M_dot
                    nrow = 12, ncol = 7, byrow = TRUE)
rebound_results %>% 
  dplyr::filter(Case == "Lamp") %>% 
  dplyr::mutate(
    Case = NULL
  ) %>% 
  ReboundTools::stages_table(label = "tab:lamp_stages_table", 
                             caption = "Results for lamp example.", 
                             digits = digs_lamp, 
                             align = "lrrrrrr") %>% 
  print(include.rownames = FALSE, 
        booktabs = TRUE,
        caption.placement = "top",
        sanitize.text.function = function(x) {x},
        format.args = list(big.mark = ","))
@


<<LampEnergyGraph, echo = FALSE, fig.cap="Energy path graph, lamp example.", fig.width=6, fig.height=4>>=
lamp_graph_params <- car_graph_params
rebound_data %>% 
  rebound_analysis() %>% 
  ReboundTools::rebound_graphs(cases = "Lamp", 
                               graph_types = "Energy", 
                               graph_params = lamp_graph_params) + 
  MKHthemes::xy_theme()
@


<<LampCostGraph, echo = FALSE, fig.cap="Cost path graph, lamp example.", fig.width=6, fig.height=4>>=
rebound_data %>% 
  rebound_analysis() %>% 
  ReboundTools::rebound_graphs(cases = "Lamp", 
                               graph_types = "Cost", 
                               graph_params = lamp_graph_params) + 
  MKHthemes::xy_theme()
@


<<LampPrefsGraph, echo = FALSE, fig.cap="Preferences path graph, lamp example.", fig.width=6, fig.height=4>>=
rebound_data %>% 
  rebound_analysis() %>% 
  ReboundTools::rebound_graphs(cases = "Lamp", 
                               graph_types = "Preferences", 
                               graph_params = lamp_graph_params) + 
  MKHthemes::xy_theme()
@


%------------------------------
\subsubsection{Results} 
\label{sec:lamp_results}
%------------------------------

The base results for the lamp upgrade are shown in Table~\ref{tab:lamp_results}.

<<lamp_rebound_results_table, results="asis", echo=FALSE>>=
rebound_results %>% 
  dplyr::filter(Case == "Lamp") %>% 
  dplyr::mutate(
    Case = NULL
  ) %>% 
  ReboundTools::rebound_results_table(include_subtotals = FALSE, 
                                      label = "tab:lamp_results", 
                                      caption = "Lamp example: rebound results.", 
                                      digits = 1, 
                                      align = "rrr") %>% 
  print(include.rownames = FALSE, 
        booktabs = TRUE,
        caption.placement = "top",
        hline.after = c(-1, 0, nrow(.)-1, nrow(.)),
        sanitize.text.function = function(x) {x},
        format.args = list(big.mark = ","))
@


% \begin{table}
% \begin{center}
% \caption{Lamp example: rebound results}
% \label{tab:lamp_results}
% \begin{tabular}{ r r }
%   \toprule
%   Rebound effect (symbol) & Value [\%] \\ 
%   \midrule
%   Emplacement effect--direct ($Re_{dempl}$) & 0.0 \\
%   Embodied energy effect--indirect ($Re_{emb}$) & --0.3 \\ 
%   Maintenance and disposal effect--indirect ($Re_{md}$) & 0.0 \\ 
%   Substitution effect--direct ($Re_{dsub}$) & 17.4 \\ 
%   Substitution effect--indirect ($Re_{isub}$) & --12.7 \\ 
%   Income effect--direct ($Re_{dinc}$) & 0.02 \\ 
%   Income effect--indirect ($Re_{iinc}$) & 24.7 \\ 
%   Macroeconomic productivity effect--indirect ($Re_{prod}$) & 24.7 \\   
% \midrule
% Total ($Re_{sum}$) & 53.9 \\
% \bottomrule
% \end{tabular}
% \end{center}
% \end{table}


Taking each of the four rebound effects in turn, 
the first is the \empleffect = -0.3\%. 
It's three parts are the direct emplacement effect = 0\%; 
the embodied energy effect (-0.3\%) which is negative, 
as although the LED lamp has higher embodied energy (+4.3MJ),
it also has a much longer lifetime, 
meaning the LED embodied energy rate (0.65MJ/year) 
is lower than for the incandescent lamp (1.23MJ/year); and
the maintenance and disposal effect is zero (0\%),
because of there is no difference in the negligible costs 
(\$0.001) assumed for the two lamps. 
Second, is the \subeffect at the original income level, 
which is split into two parts. 
The direct substitution effect yields +17.4\% value, 
due to the much higher LED lamp efficacy (82Lm/W versus 9Lm/W), 
which translates to increasing the average lamp use 
from 3 hours/day to 3 hour 30 mins per day. 
Due to the highly positive direct effect, 
the indirect substitution effect 
(remember, this is at the original income level)
must be negative and it is (-12.7\%),
as the increased lighting use from the direct substitution 
effect means that less is spent on other goods. 

Third is the \subeffect, split into two ‘income’ effects, 
where the electric lamp user respends their higher ‘effective’ income 
%(Ndot_hat 
($\rasub{N} = 15$ \$/year) which results from a net saving in outgoings
associated with the eletric lamp purchase and use.
The direct income effect (+0.02\%), 
which is positive as the lamp user allocates 
some of the additional income to increased lighting, 
but is very small. 
The indirect income effect is highly positive (+24.7\%),
due to the preference for higher spend on other goods.
So, the additional ‘effective’ income. 
Finally, the macroeconomic macroeconomic 
\prodeffect (+24.7\%) is large and positive, 
as the additional consumption of goods in the economy 
has a positive rebound multiplier effect.



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Discussion (GS, 1000 words)}
\label{sec:discussion}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Be sure to point out benefits to policy-making that emerge from the example.
+++
I'd suggest putting the criticism of 'multiplier effects'
in place of productivity effects
here as opposed to in the section with the derivation. ---GS
+++
Gregor wants to do some discussing.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Conclusions (MKH, 500 words)}
\label{sec:conclusion}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Restate characteristics of the framework.
Re-visit the benefits discussed in Section~\ref{sec:aim_contribution_structure}.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Competing interests}
\label{sec:competing_interests}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Declarations of interest: none


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Author contributions}
\label{sec:author_contributions}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\textbf{Matthew Kuperus Heun}: 
Conceptualization, 
Formal analysis, 
Resources, 
Software, 
Supervision, 
Validation,
Visualization,
Roles/Writing--original draft,
Writing--review \& editing.
\textbf{Gregor Semienuik}: 
Conceptualization, 
Formal analysis, 
Roles/Writing--original draft,
Writing--review \& editing.
\textbf{Paul Brockway}: 
Conceptualization, 
Data curation, 
Formal analysis, 
Investigation, 
Validation, 
Roles/Writing--original draft,
Writing--review \& editing.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Data repository}
\label{sec:data_repository}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

All data and calculations are stored at **** Leeds data repository URL. ****.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Acknowledgements}
\label{sec:acknowledgements}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

List funding sources in this standard way to facilitate compliance to funder's requirements:
Funding: This work was supported by the National Institutes of Health [grant numbers xxxx, yyyy]; 
the Bill \& Melinda Gates Foundation, Seattle, WA [grant number zzzz];
and the United States Institutes of Peace [grant number aaaa].

It is not necessary to include detailed descriptions on the program or type of grants and awards.
When funding is from a block grant or other resources available to
a university, college, or other research institution, 
submit the name of the institute or organization that provided the funding.

If no funding has been provided for the research, please include the following sentence:
This research did not receive any specific grant from funding agencies 
in the public, commercial, or not-for-profit sectors.

**** Also list internal reviewers. ****

Internal reviewers
Adam Marquardt (Calvin University), 
Paul Steenwyk (Calvin University), and 
****
contributed substantially to the quality of the framework and the manuscript. 

The authors benefitted from discussions with Daniele Girardi.

The authors thank the students of M.K.H.'s Fall 2019 Thermal Systems Design course (ENGR333) 
who studied energy rebound of many energy conversion devices
using an early version of this framework.

% No need for this section label, because BibTeX already provides a "References" heading.
% \section*{References}

\bibliography{HSB_refs}



\appendix
\counterwithin{figure}{section}
\counterwithin{table}{section}

% Gives a helpful "Appendix" label
\section*{Appendix}

% Labels each appendix as A, B, C, etc. instead of Appendix A, Appendix B, Appendix C, etc.
\renewcommand{\thesection}{\Alph{section}}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Nomenclature}
\label{sec:nomenclature}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/nomenclature.tex}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Derivation of comprehensive rebound framework}
\label{sec:derivation}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/derivation.tex}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Elasticities}
\label{sec:elasticities}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/elasticities.tex}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Proof: Income preference equations satisfy the budget constraint}
\label{sec:proof_income_elasticities}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/proof_income_elasticities.tex}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Utility model and derivation of $\fCs$}
\label{sec:utility_model}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/utility.tex}



\end{document}
